### PR TITLE
Fix #2 - Using buttons with multiple encoders

### LINKED ISSUE #2: Using buttons with multiple encoders
I was having issues using multiple encoder objects with their buttons.

Only the first object that runs the service function would update their value.
The actual encoder part of the object runs fine and keeps their individual positions.

My solution (not sure if ideal) was to remove the static variables keyDownTicks, doubleClickTicks, lastButtonCheck from the service function and move them to the header file.

### PR DESCRIPTION
**Pull request by ToeKnee**
Move static variable into header file to fix handling of multiple rotary
encoders with buttons.

### CODE REVIEW

**Comment by soligen2010** [comment]
Just a FYI, this fix and other bug fixes and enhancements are in the soligen2010 fork.

**Comment by 0xPIT** [comment]
Hi, thanks for your PR.

Can you help me understand how extending the scope from function to class would fix the issue you seem to be having?

As each encoder should have it's own instance of the class, and thus the function, this should not change behaviour.

Thanks.

**Comment by soligen2010** [comment]
I am afraid you are mistaken.  A static variable exists only once, and all objects will share it.  It needs to be in the header file as either public/private/protected in the class definition for each to have it's own version.

**Comment by 0xPIT** [comment]
Of course, you are right, should not write comments when I don't have time to think first.

**Pull request merged**
